# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fVBmlr <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlr`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

fVBmlrL <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlrL`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

fVBmlrNG <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlrNG`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

fVBmlrHS <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlrHS`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

fVBmlrSV <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlrSV`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

fVBmlrSVL <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlrSVL`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

fVBmlrSVNG <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlrSVNG`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

fVBmlrSVHS <- function(D, X, hyper, maxIter = 500L, Tol_ELBO = 1e-2, Tol_Par = 1e-2, Trace = 0L) {
    .Call(`_vbmlr_fVBmlrSVHS`, D, X, hyper, maxIter, Tol_ELBO, Tol_Par, Trace)
}

#' Generate samples from the model
#'
#' @param n number of samples
#' @param params list of parameters: 1) \code{Omega}: the precision matrix (\code{d x d}), 2) \code{mu}: the intercept vector (\code{d x 1}), 3) \code{Phi}: the autoregressive matrix (\code{d x d}), 4) \code{Gamma}: the regression coefficients matrix (\code{d x p})
#' @param nburn number of observations to discard before sampling
#' @param seed_set set the seed for replicability (if 0, no set seed)
#' @return \code{Y} the matrix of observations (\code{d x n})
#' @return \code{X} the matrix of exogenous covariates (independent normally distributed) (\code{p x n})
#' @export
ran_mlr <- function(n, params, nburn = 1000L, seed_set = 0L) {
    .Call(`_vbmlr_ran_mlr`, n, params, nburn, seed_set)
}

